spring:
  datasource:
    druid:
      url: jdbc:mysql://cdb-gqq4so9t.gz.tencentcdb.com:10004/transaction_mxc?useUnicode=true&characterEncoding=utf8&useSSL=false&allowPublicKeyRetrieval=true&rewriteBatchedStatements=true
zhaobi:
  token: ae0eb6aa57b4503a86f0ef861073ef55de9a5129
mocha:
  accessKey: mx0igzU8Zruhheo3Of
  secretKey: 96cdc69ea1c84eef90b7320f9c6ec8ac